config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'
  get 'users/sign_up' => 'users#new'
  post "users/sign_up" => 'users#create'
  get 'users/sign_in' => 'sessions#new'
  post 'users/sign_in' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users, only: [:show, :edit, :update]
  resources :categories
  namespace :admin do
    resources :categories, only: [:new, :create]
    resources :words, only:[:index, :new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
# frozen_string_literal: true

class Activity < ApplicationRecord
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
end

app/models/lesson.rb
# frozen_string_literal: true

class Lesson < ApplicationRecord
  has_many :lesson_words

  accepts_nested_attributes_for :words
end

app/models/lesson_word.rb
# frozen_string_literal: true

class LessonWord < ApplicationRecord
 belongs_to :lesson
 belongs_to :word
 belongs_to :word_answer
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :lessons
  mount_uploader :avatar, AvatarUploader
  has_secure_password

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                     format: { with: VALID_EMAIL_REGEX },
                     uniqueness: { case_sensitive: false }

end

app/models/word.rb
# frozen_string_literal: true

class Word < ApplicationRecord
  has_many :lesson_words
  has_many :word_answers, :dependent => :destroy

  accepts_nested_attributes_for :word_answers
end

app/models/word_answer.rb
# frozen_string_literal: true

class WordAnswer < ApplicationRecord
  belongs_to :word
  has_many :lesson_words
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

class Admin::CategoriesController < ApplicationController
  def new;end

  def create
    @category = Category.new category_params

    if @category.save
      redirect_to root_path
    else
      render :new
    end
  end

  # strong params
  private
  
  def category_params
    params.require(:category).permit :name
  end
end

app/controllers/admin/words_controller.rb
# frozen_string_literal: true

class Admin::WordsController < ApplicationController

  def index
    @word = Word.all
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:notice] = 'Thanh cong'
      redirect_to @word
    else
      render :new
    end
  end

  # strong params
  private

  def word_params
    params.require(:word).permit :content, word_answers_attributes: [:id,:content, :word_id, :correct]
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user &.authenticate(params[:session][:password])
      flash[:success] = 'Sing_in success'
      sign_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    flash[:success] = 'You are logged out'
    redirect_to users_sign_in_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Update thanh cong'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find_by id: params[:id]
  end

  def create
    @user = User.new user_params

    if @user.save
      #UserMailer.with(user: @user).welcome_email.deliver_now
      flash[:success] = 'Dang ki thanh cong'
      redirect_to root_path
    else
      flash[:success] = "Dang ki khong thanh cong"
      render :new
    end
  end

  private

  def user_params
  params.require(:user).permit :email, :fullname, :password, :password_confirmation, :avatar
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete :user_id
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/admin/categories/new.html.erb
<h1>Category</h1>
<%= form_for Category.new, url: admin_categories_path do |f| %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control',placeholder:"Enter name" %>
</div>

<%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>
<%= link_to 'Back to home', root_path %>

app/views/admin/words/new.html.erb
<% form_for Word.new, url:admin_words_path do|f|%>
  <p>
    <%= f.label :content %>
    <%= f.text_field :content %>
  </p>
  <% f.fields_for :word_answers do |builder| %>
  <p>
    <%= builder.label :content ,"word_answer" %>
    <%= builder.text_area :content %>
  </p>
  <% end %>
  <p>
    <%= f.submit 'submit' %>
  </p>
<%end%>

app/views/categories/index.html.erb
<h1>Categories</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to home', root_path,class:"btn btn-warning" %>
<%=link_to 'Create new category',new_admin_category_path,class:"btn btn-warning" %>

app/views/categories/new.html.erb
<h1>Category</h1>
<%= form_for Category.new, url: new_admin_categories_path do |f| %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control',placeholder:"Enter name" %>
</div>

<%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>
<%= link_to 'Back to home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learning</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' integrity='sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T' crossorigin='anonymous'>
<script src='https://code.jquery.com/jquery-3.3.1.slim.min.js' integrity='sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo' crossorigin='anonymous'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js' integrity='sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1' crossorigin='anonymous'></script>
<script src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js' integrity='sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM' crossorigin='anonymous'></script>
  </head>

  <body>
    <nav class='navbar navbar-expand-lg navbar-light bg-light'>
        <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarTogglerDemo02' aria-controls='navbarTogglerDemo02' aria-expanded='false' aria-label='Toggle navigation'>
          <span class='navbar-toggler-icon'></span>
        </button>
        <div class='collapse navbar-collapse' id='navbarTogglerDemo02'>
          <ul class='navbar-nav mr-auto mt-2 mt-lg-0' >

            <li class='nav-item active nav-link'>
              <%= link_to 'Home', root_path %>
            </li>

            <li class='nav-item nav-link'>
              <%= link_to 'Sign_up', users_sign_up_path %>
            </li>

            <li class='nav-item nav-link'>
              <%= link_to 'Sign_in', users_sign_in_path %>
            </li>

            <li class='nav-item nav-link'>
              <%= link_to 'Category',categories_path %>
            </li>

          </ul>
          <form class='form-inline my-2 my-lg-0'>
            <input class='form-control mr-sm-2' type='search' placeholder='Search'>
            <button class='btn btn-outline-success my-2 my-sm-0' type='submit'>Search</button>
          </form>
        </div>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save') %>
<h1>update</h1>
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_for(@user) do |f| %>
      <br>
      <%= f.label :fullname %>
      <%= f.text_field :fullname, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <br>

      <%= image_tag(@user.avatar_url) if @user.avatar? %>
      <%= f.file_field :avatar %>
      <br>

      <%= f.submit yield(:button_text), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class='container'>
  <div class='row'>
    <h1 class='title'>Sign_up</h1>
  </div>
  <div class='row'>
    <div class='col-lg-offset-3 col-lg-6'>
      <%= form_for :user, url: users_sign_up_path do |f| %>

      <div class='form-group'>
        <%= f.label :email %>
        <%= f.email_field :email, placeholder: 'Enter your email', class: 'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.label :fullname %>
        <%= f.text_field :fullname, placeholder: 'Enter your fullname', class: 'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.label :password %>
        <%= f.password_field :password, placeholder: 'Enter your password', class: 'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.label :password_confirmation%>
        <%= f.password_field :password_confirmation, placeholder: 'Enter your password ', class: 'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.label :avatar %>
        <%= f.file_field :avatar ,class:'form-control',placeholder:'Enter image'%>
      </div>

      <div class="text-center">
        <%= f.submit "sign_up", class: "btn btn-info col-lg-12" %>
      </div>

    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-lg-offset-3 col-lg-6'>
      <div class='text-left'>

        <label>
          <strong>Fulame:</strong>
          <%= @user.fullname %>
        </label>

        <br>
        <label>
          <strong>Email:</strong>
          <%= @user.email %>
        </label>

        <label>My Avatar</label>
           <%= image_tag(@user.avatar_url) if @user.avatar? %>
         </p>

       </div>
        <%= link_to 'Edit', edit_user_path(@user), class:"btn btn-primary" %>

        <%= link_to 'Logout', logout_path, method: :delete , class:"btn btn-warning" %>
       </div>
   </div>

app/views/welcome/index.html.erb
<h1>Learning</h1>